# Generated by Django 4.2.6 on 2023-11-23 11:01

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(max_length=500, null=True, upload_to=store.models.collection_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150)),
                ('description_fr', models.TextField(max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('delivery', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(max_length=500, upload_to=store.models.product_upload)),
                ('image1', models.ImageField(max_length=500, upload_to=store.models.product_upload)),
                ('image2', models.ImageField(max_length=500, upload_to=store.models.product_upload)),
                ('image3', models.ImageField(max_length=500, upload_to=store.models.product_upload)),
                ('image4', models.ImageField(max_length=500, upload_to=store.models.product_upload)),
                ('image5', models.ImageField(max_length=500, upload_to=store.models.product_upload)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_collection', to='store.collection')),
            ],
        ),
    ]
