# Generated by Django 4.2.6 on 2024-02-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_details_product_details_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
