# Generated by Django 4.2.6 on 2024-02-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=250)),
                ('title_ar', models.CharField(max_length=250)),
                ('paragraph_fr_1', models.TextField(max_length=1000, null=True)),
                ('paragraph_ar_1', models.TextField(max_length=1000, null=True)),
                ('paragraph_fr_2', models.TextField(blank=True, max_length=1000, null=True)),
                ('paragraph_ar_2', models.TextField(blank=True, max_length=1000, null=True)),
                ('paragraph_fr_3', models.TextField(blank=True, max_length=1000, null=True)),
                ('paragraph_ar_3', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='blog')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_update', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
